version: "3.1"
services:

    redis:
      image: redis:alpine
      #container_name: ${APP_NAME}-redis

    postgres:
      image: postgres:9.6-alpine
      #container_name: ${APP_NAME}-postgres
      volumes:
         - "./sourcefiles/postgres:/var/lib/postgresql/data"
      environment:
        - POSTGRES_USER=postgres #${DB_USERNAME}
        - POSTGRES_PASSWORD=M4r14Jul14123456 #${DB_PASSWORD}
        - POSTGRES_DB=$yachaywasi_db #{DB_DATABASE}
      ports:
       - "5432:5432"
      networks:
            testing_net:
                ipv4_address: 172.28.1.2
    webserver:
      image: nginx:alpine
      #container_name: ${APP_NAME}-webserver
      working_dir: /public
      volumes:
          - ./:/public
          - ./sourcefiles/nginx:/etc/nginx/conf.d
      ports:
       - "80:80"
      networks:
            testing_net:
                ipv4_address: 172.28.1.3

    php-fpm:
      #build: sourcefiles/php-fpm
      build: ./code
      #container_name: ${APP_NAME}-php-fpm
      working_dir: /app/public
      volumes:
        - ./code/:/app
        #- ./:/public
        - ./sourcefiles/php-fpm/php-ini-overrides.ini:/etc/php/7.3/fpm/conf.d/99-overrides.ini

      ports:
       - "8080:8080"

      networks:
          testing_net:
              ipv4_address: 172.28.1.4
networks:
    testing_net:
        ipam:
            driver: default
            config:
                - subnet: 172.28.0.0/16